### ISSUE TITLE
In order to get DI working, you have to provide Injectable.

### ISSUE THREAD

**Issue by lavyun** [serhiisol/node-decorators#72]
<img width="596" alt="default" src="https://user-images.githubusercontent.com/22797898/33704660-5277cfc0-db68-11e7-9179-85498511991c.png">

This is my code，but the dependency injection is failed.

### Error info
```
MissingProviderError: 
        In order to get DI working, you have to provide Injectable.
        DI attempt for UserService and dependency [object Object].
      
    at provider.deps.map (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_di@1.0.1@@decorators/di/src/container.ts:81:17)
    at Array.map (<anonymous>)
    at Function.resolveProvider (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_di@1.0.1@@decorators/di/src/containe0:13)
    at provider.deps.map (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_di@1.0.1@@decorators/di/src/container.ts:88:21)
    at Array.map (<anonymous>)
    at Function.resolveProvider (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_di@1.0.1@@decorators/di/src/containe0:13)
    at Function.get (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_di@1.0.1@@decorators/di/src/container.ts:51:17)
    at registerController (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_express@2.1.0@@decorators/express/src/exprts:32:46)
    at controllers.forEach (/Users/lavyun/Code/毕业设计项目/server/node_modules/_@decorators_express@2.1.0@@decorators/express/src/exps:19:45)
    at Array.forEach (<anonymous>)
```

**Comment by serhiisol** [comment]
Hi @lavyun, Your `UserService` injects something, and that something must be also registered via DI. Could you show me `UserService` class ?

**Comment by lavyun** [comment]
ok,this is UserService

**Comment by lavyun** [comment]
OK, This is UserService

```ts
import UserDao, {UserInter} from '../dao/UserDao'
import {Injectable} from '@decorators/di'

@Injectable()
export default class UserService {
  constructor(private userDao: UserDao) {
  }
  
  register(user: UserInter) {
    const registerRs = this.userDao.register(user)
  }
}
```

And, this is UserDao
```ts
import {getRepository} from 'typeorm'
import UserInfo from '../entities/UserInfo'
import UserAccount from '../entities/UserAccount'

export interface UserInter {
  username: string
  password: string
  email: string
  active: boolean
}


export default class UserDao {
  // 用户注册
  // TODO 事务处理
  async register(user: UserInter) {
    const userAccountRep = getRepository(UserAccount)
    const userInfoRep = getRepository(UserInfo)
    const userAccountRs = await userAccountRep.save(user)
    
    const userInfo: any = {
      username: user.username,
      sex: true,
      location: '北京市',
      birth: '1970-01-01',
      avatar: 'http://placehold.it/100x100'
    }
    const userInfoRs = await userInfoRep.save(userInfo)
    return {
      userAccountRs, userInfoRs
    }
  }
}
```

**Comment by serhiisol** [comment]
Your `UserDao` must be also injectable.

**Comment by lavyun** [comment]
Thank you very much

**Comment by serhiisol** [comment]
No problem, I hope that helped )
